spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atguigudb
    username: root
    password: Q132457q

#  security:
#    user:
#      name: "122"
#      password: "122"
server:
  port: 80